config/routes.rb
Rails.application.routes.draw do
  
  resources :subscribe_users
  resources :on_touch_users
  resources :contactos
  get 'home/index'
  get '/home', to: 'home#index'
  get '/services', to: 'service#index'
  get '/company', to: 'company#index'
  get '/expertise', to: 'expertise#index'
  get '/blog', to: 'blog#index'
  get '/services', to: 'service#index'
  get '/contact', to: 'on_touch_users#index'

  

  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/on_touch_user.rb
class OnTouchUser < ApplicationRecord
end

app/models/subscribe_user.rb
class SubscribeUser < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: [:show, :edit, :update, :destroy]

  # GET /contactos
  # GET /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1
  # GET /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos
  # POST /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to @contacto, notice: 'Contacto was successfully created.' }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1
  # PATCH/PUT /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to @contacto, notice: 'Contacto was successfully updated.' }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.json
  def destroy
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to contactos_url, notice: 'Contacto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacto_params
      params.require(:contacto).permit(:name, :email, :phone, :service_type, :stage, :budget, :timeframe, :start)
    end
end

app/controllers/expertise_controller.rb
class ExpertiseController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/on_touch_users_controller.rb
class OnTouchUsersController < ApplicationController
  before_action :set_on_touch_user, only: [:show, :edit, :update, :destroy]

  # GET /on_touch_users
  # GET /on_touch_users.json
  def index
    @on_touch_users = OnTouchUser.all
  end

  # GET /on_touch_users/1
  # GET /on_touch_users/1.json
  def show
  end

  # GET /on_touch_users/new
  def new
    @on_touch_user = OnTouchUser.new
  end

  # GET /on_touch_users/1/edit
  def edit
  end

  # POST /on_touch_users
  # POST /on_touch_users.json
  def create
    @on_touch_user = OnTouchUser.new(on_touch_user_params)

    respond_to do |format|
      if @on_touch_user.save
        format.html { redirect_to @on_touch_user, notice: 'On touch user was successfully created.' }
        format.json { render :show, status: :created, location: @on_touch_user }
      else
        format.html { render :new }
        format.json { render json: @on_touch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /on_touch_users/1
  # PATCH/PUT /on_touch_users/1.json
  def update
    respond_to do |format|
      if @on_touch_user.update(on_touch_user_params)
        format.html { redirect_to @on_touch_user, notice: 'On touch user was successfully updated.' }
        format.json { render :show, status: :ok, location: @on_touch_user }
      else
        format.html { render :edit }
        format.json { render json: @on_touch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /on_touch_users/1
  # DELETE /on_touch_users/1.json
  def destroy
    @on_touch_user.destroy
    respond_to do |format|
      format.html { redirect_to on_touch_users_url, notice: 'On touch user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_on_touch_user
      @on_touch_user = OnTouchUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def on_touch_user_params
      params.require(:on_touch_user).permit(:name, :prefix, :email)
    end
end

app/controllers/se_controller.rb
class SeController < ApplicationController
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
	
	# GET /contactos
  	# GET /contactos.json
  	def index
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/expertise_helper.rb
module ExpertiseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/on_touch_users_helper.rb
module OnTouchUsersHelper
end

app/helpers/se_helper.rb
module SeHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/subscribe_users_helper.rb
module SubscribeUsersHelper
end

app/views/contactos/_form.html.erb
<%= form_with(model: contacto, local: true) do |form| %>
  <% if contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
      <% contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :service_type %>
    <%= form.text_field :service_type %>
  </div>

  <div class="field">
    <%= form.label :stage %>
    <%= form.text_field :stage %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.text_field :budget %>
  </div>

  <div class="field">
    <%= form.label :timeframe %>
    <%= form.text_field :timeframe %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.text_field :start %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing Contacto</h1>

<%= render 'form', contacto: @contacto %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactos_path %>

app/views/contactos/index.html.erb
<div class="container-fluid text-center">
  <p id="notice"><%= notice %></p>

  <h1>Contactos</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Service type</th>
        <th>Stage</th>
        <th>Budget</th>
        <th>Timeframe</th>
        <th>Start</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contactos.each do |contacto| %>
        <tr>
          <td><%= contacto.name %></td>
          <td><%= contacto.email %></td>
          <td><%= contacto.phone %></td>
          <td><%= contacto.service_type %></td>
          <td><%= contacto.stage %></td>
          <td><%= contacto.budget %></td>
          <td><%= contacto.timeframe %></td>
          <td><%= contacto.start %></td>
          <td><%= link_to 'Show', contacto %></td>
          <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
          <td><%= link_to 'Destroy', contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Contacto', new_contacto_path %>
</div>

app/views/contactos/new.html.erb
<h1>New Contacto</h1>

<%= render 'form', contacto: @contacto %>

<%= link_to 'Back', contactos_path %>

app/views/contactos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contacto.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contacto.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contacto.phone %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @contacto.service_type %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @contacto.stage %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @contacto.budget %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @contacto.timeframe %>
</p>

<p>
  <strong>Start:</strong>
  <%= @contacto.start %>
</p>

<%= link_to 'Edit', edit_contacto_path(@contacto) %> |
<%= link_to 'Back', contactos_path %>

app/views/on_touch_users/_form.html.erb
<%= form_with(model: on_touch_user, local: true) do |form| %>
  <% if on_touch_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(on_touch_user.errors.count, "error") %> prohibited this on_touch_user from being saved:</h2>

      <ul>
      <% on_touch_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :prefix %>
    <%= form.text_field :prefix %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/on_touch_users/edit.html.erb
<h1>Editing On Touch User</h1>

<%= render 'form', on_touch_user: @on_touch_user %>

<%= link_to 'Show', @on_touch_user %> |
<%= link_to 'Back', on_touch_users_path %>

app/views/on_touch_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>On Touch Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prefix</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @on_touch_users.each do |on_touch_user| %>
      <tr>
        <td><%= on_touch_user.name %></td>
        <td><%= on_touch_user.prefix %></td>
        <td><%= on_touch_user.email %></td>
        <td><%= link_to 'Show', on_touch_user %></td>
        <td><%= link_to 'Edit', edit_on_touch_user_path(on_touch_user) %></td>
        <td><%= link_to 'Destroy', on_touch_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New On Touch User', new_on_touch_user_path %>

app/views/on_touch_users/new.html.erb
<h1>New On Touch User</h1>

<%= render 'form', on_touch_user: @on_touch_user %>

<%= link_to 'Back', on_touch_users_path %>

app/views/on_touch_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @on_touch_user.name %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @on_touch_user.prefix %>
</p>

<p>
  <strong>Email:</strong>
  <%= @on_touch_user.email %>
</p>

<%= link_to 'Edit', edit_on_touch_user_path(@on_touch_user) %> |
<%= link_to 'Back', on_touch_users_path %>