config/routes.rb
Rails.application.routes.draw do
  
  resources :subscribe_users
  resources :on_touch_users
  resources :contactos
  get 'home/index'
  get '/home', to: 'home#index'
  get '/services', to: 'service#index'
  get '/company', to: 'company#index'
  get '/expertise', to: 'expertise#index'
  get '/blog', to: 'blog#index'
  get '/services', to: 'service#index'
  get '/contact', to: 'on_touch_users#index'

  

  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/on_touch_user.rb
class OnTouchUser < ApplicationRecord
end

app/models/subscribe_user.rb
class SubscribeUser < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: [:show, :edit, :update, :destroy]

  # GET /contactos
  # GET /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1
  # GET /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos
  # POST /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to @contacto, notice: 'Contacto was successfully created.' }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1
  # PATCH/PUT /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to @contacto, notice: 'Contacto was successfully updated.' }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.json
  def destroy
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to contactos_url, notice: 'Contacto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacto_params
      params.require(:contacto).permit(:name, :email, :phone, :service_type, :stage, :budget, :timeframe, :start)
    end
end

app/controllers/expertise_controller.rb
class ExpertiseController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/se_controller.rb
class SeController < ApplicationController
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
	
	# GET /contactos
  	# GET /contactos.json
  	def index
  	end

end

app/controllers/subscribe_users_controller.rb
class SubscribeUsersController < ApplicationController
  before_action :set_subscribe_user, only: [:show, :edit, :update, :destroy]

  # GET /subscribe_users
  # GET /subscribe_users.json
  def index
    @subscribe_users = SubscribeUser.all
  end

  # GET /subscribe_users/1
  # GET /subscribe_users/1.json
  def show
  end

  # GET /subscribe_users/new
  def new
    @subscribe_user = SubscribeUser.new
  end

  # GET /subscribe_users/1/edit
  def edit
  end

  # POST /subscribe_users
  # POST /subscribe_users.json
  def create
    @subscribe_user = SubscribeUser.new(subscribe_user_params)

    respond_to do |format|
      if @subscribe_user.save
        format.html { redirect_to @subscribe_user, notice: 'Subscribe user was successfully created.' }
        format.json { render :show, status: :created, location: @subscribe_user }
      else
        format.html { render :new }
        format.json { render json: @subscribe_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribe_users/1
  # PATCH/PUT /subscribe_users/1.json
  def update
    respond_to do |format|
      if @subscribe_user.update(subscribe_user_params)
        format.html { redirect_to @subscribe_user, notice: 'Subscribe user was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscribe_user }
      else
        format.html { render :edit }
        format.json { render json: @subscribe_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribe_users/1
  # DELETE /subscribe_users/1.json
  def destroy
    @subscribe_user.destroy
    respond_to do |format|
      format.html { redirect_to subscribe_users_url, notice: 'Subscribe user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe_user
      @subscribe_user = SubscribeUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscribe_user_params
      params.require(:subscribe_user).permit(:name, :prefix, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/expertise_helper.rb
module ExpertiseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/on_touch_users_helper.rb
module OnTouchUsersHelper
end

app/helpers/se_helper.rb
module SeHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/subscribe_users_helper.rb
module SubscribeUsersHelper
end

app/views/subscribe_users/_form.html.erb
<%= form_with(model: subscribe_user, local: true) do |form| %>
  <% if subscribe_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscribe_user.errors.count, "error") %> prohibited this subscribe_user from being saved:</h2>

      <ul>
      <% subscribe_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :prefix %>
    <%= form.text_field :prefix %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribe_users/edit.html.erb
<h1>Editing Subscribe User</h1>

<%= render 'form', subscribe_user: @subscribe_user %>

<%= link_to 'Show', @subscribe_user %> |
<%= link_to 'Back', subscribe_users_path %>

app/views/subscribe_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscribe Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prefix</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribe_users.each do |subscribe_user| %>
      <tr>
        <td><%= subscribe_user.name %></td>
        <td><%= subscribe_user.prefix %></td>
        <td><%= subscribe_user.email %></td>
        <td><%= link_to 'Show', subscribe_user %></td>
        <td><%= link_to 'Edit', edit_subscribe_user_path(subscribe_user) %></td>
        <td><%= link_to 'Destroy', subscribe_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscribe User', new_subscribe_user_path %>

app/views/subscribe_users/new.html.erb
<h1>New Subscribe User</h1>

<%= render 'form', subscribe_user: @subscribe_user %>

<%= link_to 'Back', subscribe_users_path %>

app/views/subscribe_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscribe_user.name %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @subscribe_user.prefix %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscribe_user.email %>
</p>

<%= link_to 'Edit', edit_subscribe_user_path(@subscribe_user) %> |
<%= link_to 'Back', subscribe_users_path %>